[package]
name = "zetaruntime"
version = "0.1.0"
edition = "2024"

[dependencies]
papaya = "0.2.3"
libc = "0.2"
crossbeam-deque = "0.8"
once_cell = "1.21.3"
smallvec = "1.15.0"
dashmap = "7.0.0-rc2"
num_cpus = "1.17.0"
